site_name: This is a Blog of Ariey~
site_author: Ariey
repo_url: https://github.com/HLGZJY/My-Blog
repo_name: HLGZJY/My-Blog

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: null
  features:
    - content.code.copy
    - navigation.sections
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path

  palette: 
    - scheme: default
    - palette:
        primary: teal
        accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode


    - language: zh-Hant
  favicon: assets/logo.jpg

plugins:
  - search
  - tags
  - blog:
      blog_dir: .
      authors: true
      post_url_format: "{slug}"

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed: 
      alternate_style: true

nav:
  - index.md

# extra:
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Chinese (Traditional)
#       link: /zh-Hant/
#       lang: zh-Hant
#     - name: Chinese (Simplified)
#       link: /zh/
#       lang: zh