/* generated by scripts/optimize-site.js —— 勿手改 */
const CACHE = 'my-blog-1787390791645';
const PRECACHE = [
  "/My-Blog/about/index.html",
  "/My-Blog/album/daily/index.html",
  "/My-Blog/album/index.html",
  "/My-Blog/album/wallpaper/index.html",
  "/My-Blog/archives/2026/08/index.html",
  "/My-Blog/archives/2026/index.html",
  "/My-Blog/archives/index.html",
  "/My-Blog/categories/index.html",
  "/My-Blog/categories/生活/index.html",
  "/My-Blog/css/custom.css",
  "/My-Blog/css/index.css",
  "/My-Blog/css/var.css",
  "/My-Blog/img/404.jpg",
  "/My-Blog/img/album/placeholder1.svg",
  "/My-Blog/img/album/placeholder2.svg",
  "/My-Blog/img/butterfly-icon.png",
  "/My-Blog/img/error-page.png",
  "/My-Blog/img/favicon.ico",
  "/My-Blog/img/friend_404.gif",
  "/My-Blog/img/logo.jpg",
  "/My-Blog/index.html",
  "/My-Blog/js/custom.js",
  "/My-Blog/js/main.js",
  "/My-Blog/js/search/algolia.js",
  "/My-Blog/js/search/local-search.js",
  "/My-Blog/js/tw_cn.js",
  "/My-Blog/js/utils.js",
  "/My-Blog/live2d_models/shizuku/README.html",
  "/My-Blog/live2d_models/shizuku/expressions/f01.exp.json",
  "/My-Blog/live2d_models/shizuku/expressions/f02.exp.json",
  "/My-Blog/live2d_models/shizuku/expressions/f03.exp.json",
  "/My-Blog/live2d_models/shizuku/expressions/f04.exp.json",
  "/My-Blog/live2d_models/shizuku/motions/flickHead_00.mtn",
  "/My-Blog/live2d_models/shizuku/motions/flickHead_01.mtn",
  "/My-Blog/live2d_models/shizuku/motions/flickHead_02.mtn",
  "/My-Blog/live2d_models/shizuku/motions/idle_00.mtn",
  "/My-Blog/live2d_models/shizuku/motions/idle_01.mtn",
  "/My-Blog/live2d_models/shizuku/motions/idle_02.mtn",
  "/My-Blog/live2d_models/shizuku/motions/pinchIn_00.mtn",
  "/My-Blog/live2d_models/shizuku/motions/pinchIn_01.mtn",
  "/My-Blog/live2d_models/shizuku/motions/pinchIn_02.mtn",
  "/My-Blog/live2d_models/shizuku/motions/pinchOut_00.mtn",
  "/My-Blog/live2d_models/shizuku/motions/pinchOut_01.mtn",
  "/My-Blog/live2d_models/shizuku/motions/pinchOut_02.mtn",
  "/My-Blog/live2d_models/shizuku/motions/shake_00.mtn",
  "/My-Blog/live2d_models/shizuku/motions/shake_01.mtn",
  "/My-Blog/live2d_models/shizuku/motions/shake_02.mtn",
  "/My-Blog/live2d_models/shizuku/motions/tapBody_00.mtn",
  "/My-Blog/live2d_models/shizuku/motions/tapBody_01.mtn",
  "/My-Blog/live2d_models/shizuku/motions/tapBody_02.mtn",
  "/My-Blog/live2d_models/shizuku/shizuku.1024/texture_00.png",
  "/My-Blog/live2d_models/shizuku/shizuku.1024/texture_01.png",
  "/My-Blog/live2d_models/shizuku/shizuku.1024/texture_02.png",
  "/My-Blog/live2d_models/shizuku/shizuku.1024/texture_03.png",
  "/My-Blog/live2d_models/shizuku/shizuku.1024/texture_04.png",
  "/My-Blog/live2d_models/shizuku/shizuku.1024/texture_05.png",
  "/My-Blog/live2d_models/shizuku/shizuku.moc",
  "/My-Blog/live2d_models/shizuku/shizuku.model.json",
  "/My-Blog/live2d_models/shizuku/shizuku.physics.json",
  "/My-Blog/live2d_models/shizuku/shizuku.pose.json",
  "/My-Blog/live2d_models/shizuku/sounds/flickHead_00.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/flickHead_01.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/flickHead_02.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/pinchIn_00.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/pinchIn_01.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/pinchIn_02.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/pinchOut_00.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/pinchOut_01.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/pinchOut_02.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/shake_00.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/shake_01.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/shake_02.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/tapBody_00.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/tapBody_01.mp3",
  "/My-Blog/live2d_models/shizuku/sounds/tapBody_02.mp3",
  "/My-Blog/oml2d/index.min.js",
  "/My-Blog/pluginsSrc/@egjs/infinitegrid/dist/infinitegrid.min.js",
  "/My-Blog/pluginsSrc/@fortawesome/fontawesome-free/css/all.min.css",
  "/My-Blog/pluginsSrc/@fortawesome/fontawesome-free/webfonts/fa-brands-400.woff2",
  "/My-Blog/pluginsSrc/@fortawesome/fontawesome-free/webfonts/fa-regular-400.woff2",
  "/My-Blog/pluginsSrc/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2",
  "/My-Blog/pluginsSrc/@fortawesome/fontawesome-free/webfonts/fa-v4compatibility.woff2",
  "/My-Blog/pluginsSrc/@waline/client/dist/waline.css",
  "/My-Blog/pluginsSrc/@waline/client/dist/waline.js",
  "/My-Blog/pluginsSrc/abcjs/dist/abcjs-basic-min.js",
  "/My-Blog/pluginsSrc/blueimp-md5/js/md5.min.js",
  "/My-Blog/pluginsSrc/butterfly-extsrc/dist/activate-power-mode.min.js",
  "/My-Blog/pluginsSrc/butterfly-extsrc/dist/canvas-fluttering-ribbon.min.js",
  "/My-Blog/pluginsSrc/butterfly-extsrc/dist/canvas-nest.min.js",
  "/My-Blog/pluginsSrc/butterfly-extsrc/dist/canvas-ribbon.min.js",
  "/My-Blog/pluginsSrc/butterfly-extsrc/dist/click-heart.min.js",
  "/My-Blog/pluginsSrc/butterfly-extsrc/dist/click-show-text.min.js",
  "/My-Blog/pluginsSrc/butterfly-extsrc/dist/fireworks.min.js",
  "/My-Blog/pluginsSrc/butterfly-extsrc/sharejs/dist/css/share.min.css",
  "/My-Blog/pluginsSrc/butterfly-extsrc/sharejs/dist/fonts/iconfont.ttf",
  "/My-Blog/pluginsSrc/butterfly-extsrc/sharejs/dist/fonts/iconfont.woff",
  "/My-Blog/pluginsSrc/butterfly-extsrc/sharejs/dist/fonts/iconfont.woff2",
  "/My-Blog/pluginsSrc/butterfly-extsrc/sharejs/dist/js/social-share.min.js",
  "/My-Blog/pluginsSrc/chart.js/dist/chart.umd.js",
  "/My-Blog/pluginsSrc/instant.page/instantpage.js",
  "/My-Blog/pluginsSrc/katex/dist/contrib/copy-tex.min.js",
  "/My-Blog/pluginsSrc/katex/dist/katex.min.css",
  "/My-Blog/pluginsSrc/mathjax/tex-mml-chtml.js",
  "/My-Blog/pluginsSrc/mermaid/dist/mermaid.min.js",
  "/My-Blog/pluginsSrc/pjax/pjax.min.js",
  "/My-Blog/pluginsSrc/prismjs/plugins/autoloader/prism-autoloader.min.js",
  "/My-Blog/pluginsSrc/prismjs/plugins/line-numbers/prism-line-numbers.min.js",
  "/My-Blog/pluginsSrc/prismjs/prism.js",
  "/My-Blog/pluginsSrc/typed.js/dist/typed.umd.js",
  "/My-Blog/pluginsSrc/vanilla-lazyload/dist/lazyload.iife.min.js",
  "/My-Blog/posts/welcome-to-my-blog/index.html",
  "/My-Blog/search.xml",
  "/My-Blog/tags/index.html",
  "/My-Blog/tags/随笔/index.html",
  "/My-Blog/works/billing.html",
  "/My-Blog/works/gin-fullstack.html",
  "/My-Blog/works/index.html",
  "/My-Blog/works/lingxi.html",
  "/My-Blog/works/monitor.html",
  "/My-Blog/works/my-blog.html",
  "/My-Blog/works/online-lms.html",
  "/My-Blog/works/swcup.html",
  "/My-Blog/works/teacher-system.html",
  "/My-Blog/works/xiaoyitong.html"
];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  const url = new URL(req.url);
  // 导航请求：网络优先，失败回退缓存
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then((res) => {
      const copy = res.clone();
      caches.open(CACHE).then((c) => c.put(req, copy));
      return res;
    }).catch(() => caches.match(req).then((r) => r || caches.match('/My-Blog/index.html'))));
    return;
  }
  // 静态资源：缓存优先
  if (url.origin === self.location.origin && req.method === 'GET') {
    e.respondWith(caches.match(req).then((cached) => cached || fetch(req).then((res) => {
      if (res.ok) {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    })));
  }
});
